--Crear la base de datos
Create database [FacturacionDB];

Use [FacturacionDB];

--Crear la tabla de facturas

-- CREA LA TABLA DE FACTURAS
CREATE TABLE [dbo].[FACTURAS](
[IDFACTURA] [int] NOT NULL,
[FECHA] [date] NOT NULL,
[IDCLIENTE] [int] NOT NULL,
[DESCUENTO] [numeric](18, 2) NOT NULL,
[TOTAL] [numeric](18, 2) NOT NULL,
CONSTRAINT [PK_FACTURAS] PRIMARY KEY CLUSTERED
(
[IDFACTURA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF,
ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

SELECT * FROM FACTURAS

-- CREA TABLA LOG DE FACTURAS
CREATE TABLE [dbo].[FACTURA_LOGS](
[ID_REG_LOG] [int] IDENTITY(1,1) NOT NULL,
[DESC_ACCION] [varchar](500) NOT NULL,
CONSTRAINT [PK_FACTURA_LOGS] PRIMARY KEY CLUSTERED
(
[ID_REG_LOG] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF,
ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

SELECT * FROM FACTURA_LOGS

-- CREA EL TRIGGER DE LA TABLA DE FACTURAS,
-- EL CUAL SE DISPARA LUEGO DE INSERTAR UN REGISTRO
CREATE TRIGGER FACTURA_UPDATE_TRIGGER ON
FACTURAS
AFTER UPDATE
AS
BEGIN
DECLARE @DESC
VARCHAR(500) = 'Se modific el valor de ';
IF UPDATE(IDFACTURA)
SELECT @DESC =@DESC + 'IDFACTURA de '+D.IDFACTURA+' a '+I.IDFACTURA+', '
FROM INSERTED AS I,DELETED AS D;
IF UPDATE(IDCLIENTE)
SELECT @DESC=@DESC + 'IDCLIENTE de '+D.IDCLIENTE+' a '+I.IDCLIENTE+', '
FROM INSERTED AS I,DELETED AS D;
IF UPDATE(FECHA)
SELECT @DESC=@DESC + 'FECHA de '+CAST(D.FECHA AS VARCHAR) +' a '
+CAST(I.FECHA AS VARCHAR)+', '
FROM INSERTED AS I,DELETED AS D;
IF UPDATE(DESCUENTO)SELECT @DESC=@DESC + 'DESCUENTO de '
+CAST(D.DESCUENTO AS VARCHAR)+' a '+CAST(I.DESCUENTO AS VARCHAR)+', '
FROM INSERTED AS I,DELETED AS D;
IF UPDATE(TOTAL)
SELECT @DESC=@DESC + 'TOTAL de '+CAST(D.TOTAL AS VARCHAR)+' a '
+CAST(I.TOTAL AS VARCHAR)
FROM INSERTED AS I,DELETED AS D;
INSERT INTO FACTURA_LOGS
VALUES (@DESC);
END;

-- PROCESO A REALIZAR TRANSACCIONES PARA HACER QUE EL TRIGGER SE DISPARE
SELECT * FROM FACTURAS;
INSERT INTO FACTURAS (IDFACTURA, FECHA, IDCLIENTE, DESCUENTO, TOTAL)
VALUES (1, GETDATE(), 1, 5, 4500);
INSERT INTO FACTURAS (IDFACTURA, FECHA, IDCLIENTE, DESCUENTO, TOTAL)
VALUES (2, GETDATE(), 3, 2, 8500);
UPDATE FACTURAS
SET DESCUENTO = 8
WHERE IDFACTURA = 1;
UPDATE FACTURAS
SET TOTAL = 7250
WHERE IDFACTURA = 2;
-- CONFIRMO SI EL TRIGGER SE DISPARO
SELECT * FROM FACTURA_LOGS

